version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    links:
      - mongo

  react:
    build:
      context: ../
      dockerfile: ./docker/react/Dockerfile
    links:
      - backend

  mongo:
    image: plsbpm/mongodb-replica:scratch

  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - backend
      - react
    ports:
      - 80:80